### ISSUE TITLE
I think there were some changes to nvim-cmp

### ISSUE THREAD

**Issue by ddogfoodd** [vimjoyer/nixvim-video#1]
I think they changed the name of `nvim-cmp` to just `cmp`. Also `sources` and `mapping` seem removed, the code snippet in the video and this repo didn't work for me.

**Comment by ddogfoodd** [comment]
Ah yes the name has changed to `cmp` and `sources` and `mapping` have moved to `cmp.settings`.

**Comment by contini-aron** [comment]
if you need a quick copy paste replacement here is how i changed mine
```nix
      # completion
      cmp = {
	enable = true;
	autoEnableSources = true;
	settings.sources = [
	 {name = "nvim_lsp";}
	 {name = "path";}
	 {name = "buffer";}
	 {name = "luasnip";}
	];

	settings.mapping = {
	 "<CR>" = "cmp.mapping.confirm({ select = true })";
	 "<Tab>" = ''
	   cmp.mapping(
	     function(fallback)
		if cmp.visible() then
		 cmp.select_next_item()
		elseif luasnip.expandable() then
		 luasnip.expand()
		elseif luasnip.expand_or_jumpable() then
		 luasnip.expand_or_jump()
		elseif check_backspace() then
		 fallback()
		else
		 fallback()
		end
	     end
	   ,
	   { "i", "s" }
	 )
	 '';
	};
      };
```
just substitute the relevant code block and it will work

**Comment by malik-n** [comment]
> ```nix
> 	settings.mapping = {
> 	 "<CR>" = "cmp.mapping.confirm({ select = true })";
> 	 "<Tab>" = ''
> 	   cmp.mapping(
> 	     function(fallback)
> 		if cmp.visible() then
> 		 cmp.select_next_item()
> 		elseif luasnip.expandable() then
> 		 luasnip.expand()
> 		elseif luasnip.expand_or_jumpable() then
> 		 luasnip.expand_or_jump()
> 		elseif check_backspace() then
> 		 fallback()
> 		else
> 		 fallback()
> 		end
> 	     end
> 	   ,
> 	   { "i", "s" }
> 	 )
> 	 '';
> 	};
>       };
> ```
> 
This made my config build, but whenever I want to use Tab when in insert mode I get the following error:
```
E5108: Error executing lua: /nix/store/y3483dlvhw6qr8178ld0nja5di0zf504-init.lua:53: attempt to index global 'luasnip' (a nil value)
stack traceback:
        /nix/store/y3483dlvhw6qr8178ld0nja5di0zf504-init.lua:53: in function 'on_keymap'
        ...ir/pack/myNeovimPackages/start/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
        ...myNeovimPackages/start/nvim-cmp/lua/cmp/utils/keymap.lua:139: in function <...myNeovimPackages/start/nvim-cmp/lua/cmp/utils/keymap.lua:133>
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein                                                                                        
```
